// GENERATED by `python -m classroom.contracts.generate` from classroom/contracts/models.py — do not edit.
// Contract qorgau.classroom 1.1.0; student wire qorgau.class.v1 (+ additive 1.2).

export const CONTRACT_ID = "qorgau.classroom";
export const CONTRACT_VERSION = "1.1.0";
export const WIRE_PROTOCOL = "qorgau.class.v1";

export interface Ack {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "ack";
  command_id: string;
  ok: boolean;
  error_ru?: string | null;
  seq?: number | null;
  code?: AckCode | null;
  executed_at?: string | null;
  result?: Record<string, boolean | number | string | null> | null;
}

export type AckCode = "unsupported" | "invalid" | "expired" | "duplicate" | "failed" | "busy";

export interface ApiError {
  error: ApiErrorBody;
}

export interface ApiErrorBody {
  code: string;
  message_ru: string;
  details?: Record<string, unknown>;
}

export type AudioDirection = "listen" | "talk" | "both";

export interface AudioSession {
  audio_session_id: string;
  student_id: string;
  direction: AudioDirection;
  state: AudioState;
  started_by: string;
  start_command_id: string;
  stop_command_id?: string | null;
  requested_at: string;
  active_at?: string | null;
  ended_at?: string | null;
  end_reason?: string | null;
}

export interface AudioSignalIn {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "audio_signal";
  command_id: string;
  sdp?: string | null;
  ice?: string | Record<string, unknown> | null;
  audio_session_id?: string | null;
}

export interface AudioSignalOut {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type?: "audio_signal";
  command_id: string;
  sdp?: string | null;
  ice?: string | Record<string, unknown> | null;
  audio_session_id?: string | null;
}

export interface AudioStartPayload {
  direction: AudioDirection;
}

export type AudioState = "requested" | "active" | "ended" | "failed";

export type CameraState = "ok" | "busy" | "off" | "unknown";

/** v1.1 hello.capabilities. Absent = plain v1 client: only the V1_COMMAND_KINDS are offered to it. */
export interface Capabilities {
  commands?: Array<string>;
  modes?: Array<string>;
  command_progress?: boolean;
  command_expiry?: boolean;
  site_timer_pause?: boolean;
}

/** A clip uploaded by a student (binary HTTP, never JSON/base64). Storage/playback: T03. */
export interface ClipMetadata {
  clip_id: string;
  incident_id: string;
  student_id: string;
  media_type: "video/mp4" | "video/x-msvideo";
  size_bytes: number;
  sha256: string;
  uploaded_at: string;
  url: string;
  origin: DataOrigin;
}

export interface Command {
  command_id: string;
  student_id: string;
  kind: CommandKind;
  payload: Record<string, unknown>;
  issued_by: string;
  issued_at: string;
  expires_at: string;
  status: CommandStatus;
  status_at: string;
  attempts?: number;
  sent_at?: string | null;
  ack_deadline_at?: string | null;
  unconfirmed?: boolean;
  ack?: CommandAck | null;
  history?: Array<CommandStatusChange>;
}

export interface CommandAck {
  command_id: string;
  ok: boolean;
  code?: AckCode | null;
  error_ru?: string | null;
  executed_at?: string | null;
  received_at: string;
  late?: boolean;
  result?: Record<string, boolean | number | string | null> | null;
}

export interface CommandCreate {
  kind: CommandKind;
  payload?: Record<string, unknown>;
  ttl_ms?: number | null;
}

export type CommandKind = "start_exam" | "finish_exam" | "lock" | "unlock" | "request_clip" | "audio_start" | "audio_stop" | "apply_policy";

export interface CommandMsg {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type?: "command";
  command_id: string;
  kind: CommandKind;
  payload: Record<string, unknown>;
  issued_at?: string | null;
  expires_at?: string | null;
  ttl_ms?: number | null;
  attempt?: number | null;
}

export interface CommandProgress {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "command_progress";
  command_id: string;
  state: "received" | "executing";
}

export type CommandStatus = "queued" | "sent" | "received" | "succeeded" | "failed" | "expired" | "cancelled";

export interface CommandStatusChange {
  status: CommandStatus;
  at: string;
  note?: string | null;
}

export type ConnectionState = "online" | "offline";

export type DataOrigin = "real" | "simulated" | "replay" | "unknown";

/** Last `status` of a student + the server's view of it (v1 §4: server may force grey). */
export interface DeviceStatus {
  student_id: string;
  received_at?: string | null;
  sent_at?: string | null;
  exam_state?: ExamState | null;
  camera?: CameraState;
  monitoring?: MonitoringState | null;
  zone_reported?: Zone | null;
  zone?: Zone;
  zone_source?: ZoneSource;
  zone_reasons_ru?: Array<string>;
  incidents_total?: number;
  incidents_by_priority?: IncidentsByPriority;
  locked?: boolean | null;
  mic_active?: boolean | null;
  stale?: boolean;
}

export interface EmptyPayload {

}

export interface ErrorMsg {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type?: "error";
  code: string;
  message_ru: string;
}

export type EventKind = "incident";

export type ExamMode = "url" | "app";

/** What the student app opens and allows. `welcome.exam` carries the v1 subset (exam_id, title, mode, allowed_urls, allowed_apps, instructions_ru); the rest is v1.1 / T04. */
export interface ExamPolicy {
  exam_id: string;
  title: string;
  mode: ExamMode;
  allowed_urls?: Array<string>;
  allowed_apps?: Array<string>;
  instructions_ru?: string;
  policy_id?: string | null;
  version?: number | null;
  start_url?: string | null;
  auth_domains?: Array<string>;
}

export type ExamState = "idle" | "preflight" | "calibrating" | "running" | "paused" | "finished";

export interface FeatureInfo {
  name: string;
  owner: string;
  status: "mounted" | "not_installed" | "failed";
  detail?: string;
}

export interface Hello {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "hello";
  protocol: "qorgau.class.v1";
  join_code?: string | null;
  resume_token?: string | null;
  computer_name?: string;
  student_label?: string;
  app_version?: string;
  client_run_id?: string | null;
  simulated?: boolean;
  capabilities?: Capabilities | null;
  source_mode?: SourceMode | null;
  source_session_id?: string | null;
}

/** Latest state of one episode as reported by the student app (A05 fusion on the student PC). */
export interface Incident {
  incident_id: string;
  student_id: string;
  session_id: string;
  rule_id: string;
  category: string;
  priority: Priority;
  state: IncidentState;
  t_start_wall: string;
  duration_ms: number;
  explanation_ru: string;
  clip_available: boolean;
  has_snapshot: boolean;
  origin: DataOrigin;
  first_received_at: string;
  last_received_at: string;
  events: number;
}

export interface IncidentMsg {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "incident";
  seq: number;
  incident_id: string;
  rule_id: string;
  category: string;
  priority: Priority;
  state: IncidentState;
  t_start_wall: string;
  duration_ms?: number;
  explanation_ru?: string;
  clip_available?: boolean;
  snapshot_jpeg_b64?: string | null;
  event_id?: string | null;
  source_mode?: SourceMode | null;
  source_session_id?: string | null;
}

export type IncidentState = "open" | "closed";

export interface IncidentsByPriority {
  low?: number;
  medium?: number;
  high?: number;
}

export interface LockPayload {
  reason_ru: string;
}

export interface LoginRequest {
  pin: string;
}

export type MonitoringState = "ok" | "degraded";

/** One event as received from a student (persisted, deduplicated). */
export interface ObservationEvent {
  event_id: string;
  student_id: string;
  session_id: string;
  kind: EventKind;
  seq?: number | null;
  client_run_id?: string | null;
  event_time: string;
  sent_at?: string | null;
  received_at: string;
  origin: DataOrigin;
  seq_conflict?: boolean;
  payload: Record<string, unknown>;
}

export interface Ping {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type?: "ping";
}

export interface Pong {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "pong";
}

export interface Preview {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "preview";
  jpeg_b64: string;
  frame_wall: string;
  source_mode?: SourceMode | null;
  source_session_id?: string | null;
}

export type Priority = "low" | "medium" | "high";

export interface RequestClipPayload {
  incident_id: string;
}

export interface ServerInfo {
  contract?: "qorgau.classroom";
  contract_version?: string;
  wire_protocol?: "qorgau.class.v1";
  wire_extension?: string;
  server_version: string;
  server_time: string;
  session?: Session | null;
  students_online?: number;
  students_total?: number;
  simulated_students?: number;
  features?: Array<FeatureInfo>;
}

export type ServerToStudentMessage = Welcome | CommandMsg | Ping | ErrorMsg | AudioSignalOut;

export interface Session {
  session_id: string;
  title: string;
  state: "open" | "closed";
  created_at: string;
  closed_at?: string | null;
  exam: ExamPolicy;
  join_code?: string | null;
  students_total?: number;
}

export interface SessionCreate {
  title: string;
  mode: ExamMode;
  allowed_urls?: Array<string>;
  allowed_apps?: Array<string>;
  instructions_ru?: string;
  start_url?: string | null;
}

export interface SessionCreated {
  session_id: string;
  join_code: string;
  session: Session;
}

export type SourceMode = "live" | "synthetic" | "replay" | "unknown";

export interface Status {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type: "status";
  exam_state: ExamState;
  camera: CameraState;
  monitoring: MonitoringState;
  zone?: Zone | null;
  zone_reasons_ru?: Array<string>;
  incidents_total?: number;
  incidents_by_priority?: IncidentsByPriority;
  locked?: boolean;
  mic_active?: boolean;
  source_mode?: SourceMode | null;
  source_session_id?: string | null;
}

export interface Student {
  student_id: string;
  session_id: string;
  student_label: string;
  computer_name: string;
  app_version: string;
  origin: DataOrigin;
  connection: ConnectionState;
  paired_at: string;
  last_seen_at?: string | null;
  connected_since?: string | null;
  reconnects?: number;
  capabilities?: Array<string>;
}

/** One card of the class panel. FLAT, with the qorgau.class.v1 names (hello identity + status §3.1) that the T02 REAL adapter reads, plus the server's view (answers T02 request 1). `zone` is the effective zone: the server forces grey for offline / stale status / camera != ok (v1 §4); the student's own value stays in `zone_reported`. */
export interface StudentCard {
  student_id: string;
  session_id: string;
  student_label: string;
  computer_name: string;
  app_version: string;
  origin: DataOrigin;
  capabilities?: Array<string>;
  connection: ConnectionState;
  connected: boolean;
  connected_since?: string | null;
  last_seen_at?: string | null;
  reconnects?: number;
  exam_state?: ExamState | null;
  camera?: CameraState;
  monitoring?: MonitoringState | null;
  zone?: Zone;
  zone_reported?: Zone | null;
  zone_source?: ZoneSource;
  zone_reasons_ru?: Array<string>;
  incidents_total?: number;
  incidents_by_priority?: IncidentsByPriority;
  locked?: boolean | null;
  mic_active?: boolean | null;
  stale?: boolean;
  last_status_at?: string | null;
  last_event_at?: string | null;
  incidents_open?: number;
  incidents_unreviewed?: number | null;
  preview_url?: string | null;
  preview_at?: string | null;
}

export type StudentMessage = Hello | Status | IncidentMsg | Preview | Ack | CommandProgress | AudioSignalIn | Pong;

export interface TAck {
  seq: number;
  sent_at: string;
  type?: "ack";
  student_id: string;
  command_id: string;
  ok: boolean;
  error_ru?: string | null;
}

export interface TAudioSignal {
  seq: number;
  sent_at: string;
  type?: "audio_signal";
  student_id: string;
  command_id: string;
  audio_session_id?: string | null;
  sdp?: string | null;
  ice?: string | Record<string, unknown> | null;
}

export interface TAudioUpdate {
  seq: number;
  sent_at: string;
  type?: "audio_session_update";
  audio: AudioSession;
}

export interface TCommandUpdate {
  seq: number;
  sent_at: string;
  type?: "command_update";
  command: Command;
}

/** Answer to a rejected teacher->server message on /ws/teacher (the connection stays open). */
export interface TError {
  seq: number;
  sent_at: string;
  type?: "error";
  code: string;
  message_ru: string;
}

/** Generic channel for mounted features (T03 history changes, T04 exam/command views, T05 audio). */
export interface TFeatureEvent {
  seq: number;
  sent_at: string;
  type?: "feature_event";
  feature: string;
  event: string;
  data: Record<string, unknown>;
}

export interface THello {
  seq: number;
  sent_at: string;
  type?: "hello";
  info: ServerInfo;
}

export interface TIncident {
  seq: number;
  sent_at: string;
  type?: "incident";
  student_id: string;
  incident: Incident;
  duplicate?: boolean;
}

/** Preview METADATA; fetch the JPEG from `url`. `jpeg_b64` only with ?inline_previews=1 (legacy v1 panel). */
export interface TPreview {
  seq: number;
  sent_at: string;
  type?: "preview";
  student_id: string;
  preview_seq: number;
  frame_wall: string;
  received_at: string;
  byte_length: number;
  url: string;
  origin: DataOrigin;
  jpeg_b64?: string | null;
}

export interface TResync {
  seq: number;
  sent_at: string;
  type?: "resync_required";
  reason: "queue_overflow" | "server_restart";
}

export interface TSessionUpdate {
  seq: number;
  sent_at: string;
  type?: "session_update";
  session: Session | null;
}

export interface TSnapshot {
  seq: number;
  sent_at: string;
  type?: "snapshot";
  students: Array<StudentCard>;
}

export interface TStudentUpdate {
  seq: number;
  sent_at: string;
  type?: "student_update";
  student: StudentCard;
}

/** Teacher -> server over /ws/teacher (relayed to exactly one student; v1 §6). */
export interface TeacherAudioSignal {
  type: "audio_signal";
  student_id: string;
  command_id: string;
  audio_session_id?: string | null;
  sdp?: string | null;
  ice?: string | Record<string, unknown> | null;
}

export type TeacherStreamMessage = THello | TSnapshot | TStudentUpdate | TIncident | TPreview | TCommandUpdate | TAck | TAudioUpdate | TAudioSignal | TSessionUpdate | TFeatureEvent | TResync | TError;

export interface Welcome {
  v?: 1;
  msg_id: string;
  sent_at: string;
  type?: "welcome";
  student_id: string;
  resume_token: string;
  server_time: string;
  exam: ExamPolicy;
  session_id?: string | null;
  resumed?: boolean;
}

export type Zone = "green" | "yellow" | "red" | "grey";

export type ZoneSource = "student" | "server_stale" | "server_camera" | "server_offline" | "none";
