// GENERATED by proctoring/contracts/tools/generate.py from proctor_contracts/v1.py.
// DO NOT EDIT. Owner: A01. Change requests: proctoring/handoffs/Axx/DEPENDENCIES.txt
// Contract fixtures (marked synthetic data), typed with `satisfies` so tsc checks them.
import type { AnswerRecord, AnswerUpsert, ApiError, AttentionObservation, CalibrationState, EnvironmentCapabilities, EnvironmentEventAck, EnvironmentEventBatch, EnvironmentObservation, ExamDefinition, ExportManifest, FramePacketMeta, HealthObservation, HealthReport, HumanReview, HumanReviewCreate, Incident, IncidentChange, IncidentDetail, ModelManifest, PhoneObservation, PreflightReport, PreviewFrameMeta, RuntimeMetrics, SessionCreate, SessionInfo, SessionSummary, SourceConfig, StreamEnvelope } from "./qorgau-v1.generated";

export const fixtures = {
  "AnswerRecord.single": {
    "session_id": "fx-session-0001",
    "question_id": "q1",
    "value": [
      "b"
    ],
    "client_seq": 3,
    "saved_at": "2026-10-09T09:00:45Z"
  } satisfies AnswerRecord,
  "AnswerUpsert.single": {
    "value": [
      "b"
    ],
    "client_seq": 3
  } satisfies AnswerUpsert,
  "ApiError.invalid_state": {
    "error": {
      "code": "INVALID_STATE",
      "message": "Cannot start: session is in state 'created'",
      "retryable": false,
      "details": {
        "state": "created",
        "action": "start"
      }
    }
  } satisfies ApiError,
  "AttentionObservation.gaze_down": {
    "observation_id": "fx-att-121",
    "session_id": "fx-session-0001",
    "frame_id": 121,
    "t_session_ms": 4033.3,
    "wall_time": "2026-10-09T09:00:04.033300Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "attention",
      "version": "fixture-1",
      "model_id": "fixture-face",
      "model_sha256": null,
      "config_version": null
    },
    "status": "ok",
    "quality": 0.75,
    "quality_flags": [],
    "latency_ms": 40.0,
    "kind": "attention",
    "face_count": 1,
    "faces": [
      {
        "bbox": {
          "x_min": 0.35,
          "y_min": 0.15,
          "x_max": 0.62,
          "y_max": 0.55
        },
        "confidence": 0.93,
        "is_primary": true
      }
    ],
    "primary_face_present": true,
    "head_pose": {
      "yaw_deg": 3.0,
      "pitch_deg": -24.0,
      "roll_deg": 1.5
    },
    "head_direction": "down",
    "gaze": {
      "direction": "down",
      "yaw_deg": 2.0,
      "pitch_deg": -28.0,
      "confidence": 0.6,
      "method": "fused",
      "calibrated": true
    },
    "calibration_id": "fx-cal-1",
    "reasons": [
      "pitch_below_calibrated_down"
    ]
  } satisfies AttentionObservation,
  "AttentionObservation.two_faces": {
    "observation_id": "fx-att-400",
    "session_id": "fx-session-0001",
    "frame_id": 400,
    "t_session_ms": 13333.3,
    "wall_time": "2026-10-09T09:00:13.333300Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "attention",
      "version": "fixture-1",
      "model_id": "fixture-face",
      "model_sha256": null,
      "config_version": null
    },
    "status": "ok",
    "quality": 0.7,
    "quality_flags": [],
    "latency_ms": null,
    "kind": "attention",
    "face_count": 2,
    "faces": [
      {
        "bbox": {
          "x_min": 0.35,
          "y_min": 0.15,
          "x_max": 0.62,
          "y_max": 0.55
        },
        "confidence": 0.92,
        "is_primary": true
      },
      {
        "bbox": {
          "x_min": 0.75,
          "y_min": 0.1,
          "x_max": 0.95,
          "y_max": 0.4
        },
        "confidence": 0.81,
        "is_primary": false
      }
    ],
    "primary_face_present": true,
    "head_pose": {
      "yaw_deg": 1.0,
      "pitch_deg": -2.0,
      "roll_deg": 0.0
    },
    "head_direction": "center",
    "gaze": {
      "direction": "center",
      "yaw_deg": null,
      "pitch_deg": null,
      "confidence": 0.7,
      "method": "fused",
      "calibrated": true
    },
    "calibration_id": "fx-cal-1",
    "reasons": []
  } satisfies AttentionObservation,
  "AttentionObservation.unknown_low_light": {
    "observation_id": "fx-att-300",
    "session_id": "fx-session-0001",
    "frame_id": 300,
    "t_session_ms": 10000.0,
    "wall_time": "2026-10-09T09:00:10Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "attention",
      "version": "fixture-1",
      "model_id": "fixture-face",
      "model_sha256": null,
      "config_version": null
    },
    "status": "unknown",
    "quality": 0.1,
    "quality_flags": [
      "low_light"
    ],
    "latency_ms": null,
    "kind": "attention",
    "face_count": null,
    "faces": [],
    "primary_face_present": null,
    "head_pose": null,
    "head_direction": "unknown",
    "gaze": {
      "direction": "unknown",
      "yaw_deg": null,
      "pitch_deg": null,
      "confidence": null,
      "method": "head_pose_only",
      "calibrated": true
    },
    "calibration_id": null,
    "reasons": [
      "landmarks_not_found_low_light"
    ]
  } satisfies AttentionObservation,
  "CalibrationState.collecting": {
    "calibration_id": "fx-cal-1",
    "phase": "collecting",
    "targets": [
      {
        "target": "center",
        "state": "ok",
        "samples": 30,
        "required_samples": 30,
        "quality": 0.82,
        "message_code": null
      },
      {
        "target": "left",
        "state": "collecting",
        "samples": 12,
        "required_samples": 30,
        "quality": 0.7,
        "message_code": null
      },
      {
        "target": "right",
        "state": "pending",
        "samples": 0,
        "required_samples": 30,
        "quality": null,
        "message_code": null
      },
      {
        "target": "up",
        "state": "pending",
        "samples": 0,
        "required_samples": 30,
        "quality": null,
        "message_code": null
      },
      {
        "target": "down",
        "state": "pending",
        "samples": 0,
        "required_samples": 30,
        "quality": null,
        "message_code": null
      }
    ],
    "current_target": "left",
    "message_code": null,
    "updated_at": "2026-10-09T09:00:09Z"
  } satisfies CalibrationState,
  "EnvironmentCapabilities.unverified": {
    "reported_at": "2026-10-09T09:00:00.100000Z",
    "platform": "win32 10.0.22631 (fixture)",
    "shell_version": "0.1.0",
    "exam_mode_supported": true,
    "items": [
      {
        "action": "shortcut_ctrl_c",
        "status": "blocked",
        "mechanism": "electron.before_input_event",
        "verified_on": null,
        "note_ru": "Только внутри окна экзамена"
      },
      {
        "action": "shortcut_alt_tab",
        "status": "unverified",
        "mechanism": "none",
        "verified_on": null,
        "note_ru": "Нужна проверка на целевой Windows"
      }
    ]
  } satisfies EnvironmentCapabilities,
  "EnvironmentEventAck.one": {
    "accepted": 1,
    "duplicates": 0,
    "observation_ids": [
      "env-fx-session-0001-7"
    ]
  } satisfies EnvironmentEventAck,
  "EnvironmentEventBatch.alt_tab": {
    "session_id": "fx-session-0001",
    "events": [
      {
        "action": "shortcut_alt_tab",
        "enforcement": "detected_only",
        "mechanism": "electron.blur_event",
        "scope": "window",
        "client_seq": 7,
        "client_wall_time": "2026-10-09T09:00:14.998000Z",
        "detail": {
          "process_name": null,
          "shortcut": "Alt+Tab",
          "duration_ms": null
        }
      }
    ]
  } satisfies EnvironmentEventBatch,
  "EnvironmentObservation.alt_tab_detected": {
    "observation_id": "fx-env-7",
    "session_id": "fx-session-0001",
    "frame_id": null,
    "t_session_ms": 15000.0,
    "wall_time": "2026-10-09T09:00:15Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "environment",
      "version": "fixture-1",
      "model_id": null,
      "model_sha256": null,
      "config_version": null
    },
    "status": "ok",
    "quality": null,
    "quality_flags": [],
    "latency_ms": null,
    "kind": "environment",
    "action": "shortcut_alt_tab",
    "enforcement": "detected_only",
    "mechanism": "electron.blur_event",
    "scope": "window",
    "client_seq": 7,
    "client_wall_time": "2026-10-09T09:00:14.998000Z",
    "detail": {
      "process_name": null,
      "shortcut": "Alt+Tab",
      "duration_ms": null
    }
  } satisfies EnvironmentObservation,
  "ExamDefinition.demo_min": {
    "exam_id": "demo-exam-1",
    "title": "Демонстрационный тест (fixture)",
    "locale": "ru",
    "duration_s": 600,
    "is_demo": true,
    "questions": [
      {
        "question_id": "q1",
        "kind": "single_choice",
        "prompt": "Сколько байт в одном килобайте (KiB)?",
        "options": [
          {
            "option_id": "a",
            "text": "1000"
          },
          {
            "option_id": "b",
            "text": "1024"
          }
        ],
        "max_length": null
      },
      {
        "question_id": "q2",
        "kind": "short_text",
        "prompt": "Назовите протокол, используемый для веб-страниц.",
        "options": [],
        "max_length": 200
      }
    ]
  } satisfies ExamDefinition,
  "ExportManifest.example": {
    "contract": "qorgau.v1",
    "contract_version": "1.0.0",
    "exported_at": "2026-10-09T09:11:40Z",
    "session_id": "fx-session-0001",
    "source_mode": "synthetic",
    "backend_version": "0.1.0",
    "config_versions": {
      "fusion": "fixture-config-1"
    },
    "models": [],
    "files": [
      {
        "name": "report.html",
        "media_type": "text/html",
        "sha256": "0000000000000000000000000000000000000000000000000000000000000000",
        "size_bytes": 12345
      }
    ],
    "limitations_ru": [
      "Хэш не защищает от изменения владельцем компьютера"
    ]
  } satisfies ExportManifest,
  "FramePacketMeta.synthetic": {
    "session_id": "fx-session-0001",
    "frame_id": 120,
    "t_session_ms": 4000.0,
    "wall_time": "2026-10-09T09:00:04Z",
    "t_capture_mono_ns": 123456789000,
    "width": 640,
    "height": 480,
    "color_format": "BGR",
    "mirrored": false,
    "source_mode": "synthetic",
    "source_id": "synthetic:bootstrap"
  } satisfies FramePacketMeta,
  "HealthObservation.camera_disconnected": {
    "observation_id": "fx-health-1",
    "session_id": "fx-session-0001",
    "frame_id": null,
    "t_session_ms": 20000.0,
    "wall_time": "2026-10-09T09:00:20Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "capture",
      "version": "fixture-1",
      "model_id": null,
      "model_sha256": null,
      "config_version": null
    },
    "status": "error",
    "quality": null,
    "quality_flags": [],
    "latency_ms": null,
    "kind": "health",
    "health": {
      "component": "capture",
      "status": "error",
      "code": "camera_disconnected",
      "message": "Camera stopped delivering frames",
      "since_t_session_ms": 20000.0,
      "details": {
        "last_frame_id": 599
      }
    }
  } satisfies HealthObservation,
  "HealthReport.bootstrap": {
    "backend_version": "0.1.0",
    "contract_version": "1.0.0",
    "overall": "degraded",
    "components": [
      {
        "component": "backend",
        "status": "ok",
        "code": "ok",
        "message": "",
        "since_t_session_ms": null,
        "details": {}
      },
      {
        "component": "phone",
        "status": "unavailable",
        "code": "module_not_integrated",
        "message": "proctor.phone is not integrated in this build",
        "since_t_session_ms": null,
        "details": {}
      }
    ],
    "active_session_id": null,
    "server_time": "2026-10-09T09:00:00.500000Z"
  } satisfies HealthReport,
  "HumanReview.dismissed": {
    "review_id": "fx-rev-1",
    "session_id": "fx-session-0001",
    "incident_id": "fx-inc-1",
    "decision": "dismissed",
    "comment": "Телефон лежал на столе экраном вниз.",
    "operator": "teacher-demo",
    "created_at": "2026-10-09T09:01:00Z",
    "supersedes_review_id": null
  } satisfies HumanReview,
  "HumanReviewCreate.dismiss": {
    "decision": "dismissed",
    "comment": "Телефон лежал на столе экраном вниз.",
    "operator": "teacher-demo"
  } satisfies HumanReviewCreate,
  "Incident.phone_visible_open": {
    "incident_id": "fx-inc-1",
    "session_id": "fx-session-0001",
    "rule_id": "phone_visible",
    "category": "phone",
    "state": "open",
    "priority": "medium",
    "t_start_ms": 2400.0,
    "t_end_ms": null,
    "wall_start": "2026-10-09T09:00:02.400000Z",
    "wall_end": null,
    "duration_ms": 1600.0,
    "source_mode": "synthetic",
    "max_confidence": 0.71,
    "mean_quality": 0.8,
    "explanation": {
      "summary_ru": "Телефон виден 1,6 с; требуется проверка преподавателем.",
      "summary_kk": null,
      "facts": [
        {
          "key": "phone_visible_ms",
          "value": 1600.0,
          "unit": "ms",
          "label_ru": "Телефон виден"
        }
      ],
      "caveats_ru": [
        "Обнаружение телефона не доказывает фотографирование экрана."
      ]
    },
    "observation_ids": [
      "fx-phone-120"
    ],
    "observation_count": 48,
    "trigger_frame_id": 120,
    "related_incident_ids": [],
    "evidence_ids": [],
    "rule_version": "fixture-rules-1",
    "config_version": "fixture-config-1",
    "end_reason": null,
    "update_seq": 1,
    "review_status": "pending"
  } satisfies Incident,
  "IncidentChange.opened": {
    "change": "opened",
    "incident": {
      "incident_id": "fx-inc-1",
      "session_id": "fx-session-0001",
      "rule_id": "phone_visible",
      "category": "phone",
      "state": "open",
      "priority": "medium",
      "t_start_ms": 2400.0,
      "t_end_ms": null,
      "wall_start": "2026-10-09T09:00:02.400000Z",
      "wall_end": null,
      "duration_ms": 1600.0,
      "source_mode": "synthetic",
      "max_confidence": 0.71,
      "mean_quality": 0.8,
      "explanation": {
        "summary_ru": "Телефон виден 1,6 с; требуется проверка преподавателем.",
        "summary_kk": null,
        "facts": [
          {
            "key": "phone_visible_ms",
            "value": 1600.0,
            "unit": "ms",
            "label_ru": "Телефон виден"
          }
        ],
        "caveats_ru": [
          "Обнаружение телефона не доказывает фотографирование экрана."
        ]
      },
      "observation_ids": [
        "fx-phone-120"
      ],
      "observation_count": 48,
      "trigger_frame_id": 120,
      "related_incident_ids": [],
      "evidence_ids": [],
      "rule_version": "fixture-rules-1",
      "config_version": "fixture-config-1",
      "end_reason": null,
      "update_seq": 1,
      "review_status": "pending"
    }
  } satisfies IncidentChange,
  "IncidentDetail.with_review": {
    "incident": {
      "incident_id": "fx-inc-1",
      "session_id": "fx-session-0001",
      "rule_id": "phone_visible",
      "category": "phone",
      "state": "open",
      "priority": "medium",
      "t_start_ms": 2400.0,
      "t_end_ms": null,
      "wall_start": "2026-10-09T09:00:02.400000Z",
      "wall_end": null,
      "duration_ms": 1600.0,
      "source_mode": "synthetic",
      "max_confidence": 0.71,
      "mean_quality": 0.8,
      "explanation": {
        "summary_ru": "Телефон виден 1,6 с; требуется проверка преподавателем.",
        "summary_kk": null,
        "facts": [
          {
            "key": "phone_visible_ms",
            "value": 1600.0,
            "unit": "ms",
            "label_ru": "Телефон виден"
          }
        ],
        "caveats_ru": [
          "Обнаружение телефона не доказывает фотографирование экрана."
        ]
      },
      "observation_ids": [
        "fx-phone-120"
      ],
      "observation_count": 48,
      "trigger_frame_id": 120,
      "related_incident_ids": [],
      "evidence_ids": [
        "fx-ev-1"
      ],
      "rule_version": "fixture-rules-1",
      "config_version": "fixture-config-1",
      "end_reason": null,
      "update_seq": 1,
      "review_status": "dismissed"
    },
    "reviews": [
      {
        "review_id": "fx-rev-1",
        "session_id": "fx-session-0001",
        "incident_id": "fx-inc-1",
        "decision": "dismissed",
        "comment": "Телефон лежал на столе экраном вниз.",
        "operator": "teacher-demo",
        "created_at": "2026-10-09T09:01:00Z",
        "supersedes_review_id": null
      }
    ],
    "evidence": [
      {
        "evidence_id": "fx-ev-1",
        "session_id": "fx-session-0001",
        "incident_id": "fx-inc-1",
        "kind": "snapshot",
        "frame_id": 120,
        "t_session_ms": 4000.0,
        "media_type": "image/jpeg",
        "sha256": "0000000000000000000000000000000000000000000000000000000000000000",
        "size_bytes": 28311,
        "created_at": "2026-10-09T09:00:04.100000Z"
      }
    ]
  } satisfies IncidentDetail,
  "ModelManifest.example_only": {
    "model_id": "example-detector",
    "module": "phone",
    "task": "object_detection",
    "file": "phone/example.onnx",
    "format": "onnx",
    "version": "EXAMPLE",
    "source_url": "https://example.invalid/not-a-real-model",
    "license": "EXAMPLE",
    "sha256": "0000000000000000000000000000000000000000000000000000000000000000",
    "size_bytes": 1,
    "input_size": [
      640,
      640
    ],
    "class_names": {
      "67": "cell phone"
    },
    "prepared_at": "2026-10-09T09:00:00Z",
    "notes": "FIXTURE ONLY: not a real model, hash is a placeholder"
  } satisfies ModelManifest,
  "PhoneObservation.phone_visible": {
    "observation_id": "fx-phone-120",
    "session_id": "fx-session-0001",
    "frame_id": 120,
    "t_session_ms": 4000.0,
    "wall_time": "2026-10-09T09:00:04Z",
    "source_mode": "synthetic",
    "producer": {
      "module": "phone",
      "version": "fixture-1",
      "model_id": "fixture-detector",
      "model_sha256": null,
      "config_version": null
    },
    "status": "ok",
    "quality": 0.8,
    "quality_flags": [],
    "latency_ms": 85.0,
    "kind": "phone",
    "detections": [
      {
        "bbox": {
          "x_min": 0.42,
          "y_min": 0.55,
          "x_max": 0.52,
          "y_max": 0.78
        },
        "confidence": 0.71,
        "class_name": "cell phone",
        "class_index": 67,
        "track_id": "trk-1",
        "track_quality": 0.9,
        "track_age_ms": 1600.0
      }
    ],
    "signals": [
      {
        "name": "phone_visible",
        "state": "present",
        "confidence": 0.71,
        "track_id": "trk-1",
        "reason": "detected_in_frame",
        "facts": {
          "visible_ms": 1600.0
        }
      },
      {
        "name": "phone_raised",
        "state": "absent",
        "confidence": null,
        "track_id": "trk-1",
        "reason": "track_below_raise_zone",
        "facts": {
          "rise_ratio": 0.03
        }
      },
      {
        "name": "possible_screen_capture",
        "state": "insufficient_evidence",
        "confidence": null,
        "track_id": null,
        "reason": "camera_side_not_observable",
        "facts": {}
      }
    ]
  } satisfies PhoneObservation,
  "PreflightReport.synthetic": {
    "session_id": "fx-session-0001",
    "source_mode": "synthetic",
    "checks": [
      {
        "check_id": "backend",
        "status": "pass",
        "required": true,
        "message_code": "backend_ok",
        "message_ru": "Локальный сервис работает",
        "details": {}
      },
      {
        "check_id": "camera",
        "status": "pass",
        "required": true,
        "message_code": "synthetic_source",
        "message_ru": "СИНТЕТИЧЕСКИЙ источник кадров (не камера)",
        "details": {}
      },
      {
        "check_id": "phone_model",
        "status": "warn",
        "required": false,
        "message_code": "synthetic_script",
        "message_ru": "Сценарные синтетические наблюдения, не CV",
        "details": {}
      },
      {
        "check_id": "environment_protection",
        "status": "not_run",
        "required": false,
        "message_code": "shell_not_reported",
        "message_ru": "Оболочка не сообщила возможности защиты",
        "details": {}
      }
    ],
    "ready": true,
    "created_at": "2026-10-09T09:00:01Z"
  } satisfies PreflightReport,
  "PreviewFrameMeta.synthetic": {
    "session_id": "fx-session-0001",
    "frame_id": 120,
    "t_session_ms": 4000.0,
    "wall_time": "2026-10-09T09:00:04Z",
    "width": 640,
    "height": 480,
    "mirrored": false,
    "source_mode": "synthetic",
    "media_type": "image/jpeg",
    "byte_length": 28311
  } satisfies PreviewFrameMeta,
  "RuntimeMetrics.synthetic": {
    "session_id": "fx-session-0001",
    "t_session_ms": 30000.0,
    "window_s": 5.0,
    "capture_fps": 29.8,
    "frames_captured": 900,
    "frames_dropped": 0,
    "consumers": [
      {
        "name": "phone",
        "processed_fps": 7.9,
        "frames_processed": 230,
        "frames_skipped": 660,
        "errors": 0,
        "frame_age_ms_p50": 20.0,
        "frame_age_ms_p95": 41.0,
        "process_ms_p50": 95.0,
        "process_ms_p95": 130.0
      }
    ],
    "e2e_latency_ms_p50": 120.0,
    "e2e_latency_ms_p95": 170.0
  } satisfies RuntimeMetrics,
  "SessionCreate.synthetic": {
    "source": {
      "mode": "synthetic",
      "camera_index": 0,
      "replay_id": null,
      "width": 640,
      "height": 480,
      "fps": 30
    },
    "exam_id": "demo-exam-1",
    "student_label": "student-demo",
    "consent": {
      "accepted": true,
      "text_version": "consent-ru-1",
      "accepted_at": "2026-10-09T09:00:00Z"
    },
    "retain_media": false
  } satisfies SessionCreate,
  "SessionInfo.running": {
    "session_id": "fx-session-0001",
    "state": "running",
    "source": {
      "mode": "synthetic",
      "camera_index": 0,
      "replay_id": null,
      "width": 640,
      "height": 480,
      "fps": 30
    },
    "source_mode": "synthetic",
    "exam_id": "demo-exam-1",
    "student_label": "student-demo",
    "retain_media": false,
    "created_at": "2026-10-09T09:00:00Z",
    "started_at": "2026-10-09T09:00:30Z",
    "finished_at": null,
    "exam_started_t_ms": 30000.0,
    "paused_total_ms": 0.0,
    "calibration": {
      "calibration_id": "fx-cal-1",
      "phase": "skipped",
      "targets": [
        {
          "target": "center",
          "state": "ok",
          "samples": 30,
          "required_samples": 30,
          "quality": 0.82,
          "message_code": null
        },
        {
          "target": "left",
          "state": "collecting",
          "samples": 12,
          "required_samples": 30,
          "quality": 0.7,
          "message_code": null
        },
        {
          "target": "right",
          "state": "pending",
          "samples": 0,
          "required_samples": 30,
          "quality": null,
          "message_code": null
        },
        {
          "target": "up",
          "state": "pending",
          "samples": 0,
          "required_samples": 30,
          "quality": null,
          "message_code": null
        },
        {
          "target": "down",
          "state": "pending",
          "samples": 0,
          "required_samples": 30,
          "quality": null,
          "message_code": null
        }
      ],
      "current_target": "left",
      "message_code": "skipped_by_operator",
      "updated_at": "2026-10-09T09:00:09Z"
    },
    "contract_version": "1.0.0",
    "backend_version": "0.1.0",
    "last_error": null
  } satisfies SessionInfo,
  "SessionSummary.finished": {
    "session": {
      "session_id": "fx-session-0001",
      "state": "finished",
      "source": {
        "mode": "synthetic",
        "camera_index": 0,
        "replay_id": null,
        "width": 640,
        "height": 480,
        "fps": 30
      },
      "source_mode": "synthetic",
      "exam_id": "demo-exam-1",
      "student_label": "student-demo",
      "retain_media": false,
      "created_at": "2026-10-09T09:00:00Z",
      "started_at": "2026-10-09T09:00:30Z",
      "finished_at": "2026-10-09T09:10:00Z",
      "exam_started_t_ms": 30000.0,
      "paused_total_ms": 0.0,
      "calibration": {
        "calibration_id": "fx-cal-1",
        "phase": "skipped",
        "targets": [
          {
            "target": "center",
            "state": "ok",
            "samples": 30,
            "required_samples": 30,
            "quality": 0.82,
            "message_code": null
          },
          {
            "target": "left",
            "state": "collecting",
            "samples": 12,
            "required_samples": 30,
            "quality": 0.7,
            "message_code": null
          },
          {
            "target": "right",
            "state": "pending",
            "samples": 0,
            "required_samples": 30,
            "quality": null,
            "message_code": null
          },
          {
            "target": "up",
            "state": "pending",
            "samples": 0,
            "required_samples": 30,
            "quality": null,
            "message_code": null
          },
          {
            "target": "down",
            "state": "pending",
            "samples": 0,
            "required_samples": 30,
            "quality": null,
            "message_code": null
          }
        ],
        "current_target": "left",
        "message_code": "skipped_by_operator",
        "updated_at": "2026-10-09T09:00:09Z"
      },
      "contract_version": "1.0.0",
      "backend_version": "0.1.0",
      "last_error": null
    },
    "desk_scan": null,
    "observed_ms": 560000.0,
    "paused_ms": 0.0,
    "gaps": [
      {
        "t_start_ms": 20000.0,
        "t_end_ms": 23000.0,
        "component": "capture",
        "reason": "camera_disconnected"
      }
    ],
    "incidents_total": 1,
    "incidents_by_rule": {
      "phone_visible": 1
    },
    "reviews_by_decision": {
      "dismissed": 1
    },
    "limitations_ru": [
      "Синтетические данные"
    ],
    "review_zone": null,
    "review_zone_reasons_ru": [],
    "review_zone_rule_version": null
  } satisfies SessionSummary,
  "SourceConfig.synthetic": {
    "mode": "synthetic",
    "camera_index": 0,
    "replay_id": null,
    "width": 640,
    "height": 480,
    "fps": 30
  } satisfies SourceConfig,
  "StreamEnvelope.hello": {
    "contract": "qorgau.v1",
    "seq": 0,
    "sent_at": "2026-10-09T09:00:00Z",
    "session_id": null,
    "message": {
      "type": "hello",
      "contract": "qorgau.v1",
      "contract_version": "1.0.0",
      "backend_version": "0.1.0",
      "server_time": "2026-10-09T09:00:00Z"
    }
  } satisfies StreamEnvelope,
  "StreamEnvelope.incident_opened": {
    "contract": "qorgau.v1",
    "seq": 42,
    "sent_at": "2026-10-09T09:00:04.010000Z",
    "session_id": "fx-session-0001",
    "message": {
      "type": "incident",
      "change": {
        "change": "opened",
        "incident": {
          "incident_id": "fx-inc-1",
          "session_id": "fx-session-0001",
          "rule_id": "phone_visible",
          "category": "phone",
          "state": "open",
          "priority": "medium",
          "t_start_ms": 2400.0,
          "t_end_ms": null,
          "wall_start": "2026-10-09T09:00:02.400000Z",
          "wall_end": null,
          "duration_ms": 1600.0,
          "source_mode": "synthetic",
          "max_confidence": 0.71,
          "mean_quality": 0.8,
          "explanation": {
            "summary_ru": "Телефон виден 1,6 с; требуется проверка преподавателем.",
            "summary_kk": null,
            "facts": [
              {
                "key": "phone_visible_ms",
                "value": 1600.0,
                "unit": "ms",
                "label_ru": "Телефон виден"
              }
            ],
            "caveats_ru": [
              "Обнаружение телефона не доказывает фотографирование экрана."
            ]
          },
          "observation_ids": [
            "fx-phone-120"
          ],
          "observation_count": 48,
          "trigger_frame_id": 120,
          "related_incident_ids": [],
          "evidence_ids": [],
          "rule_version": "fixture-rules-1",
          "config_version": "fixture-config-1",
          "end_reason": null,
          "update_seq": 1,
          "review_status": "pending"
        }
      }
    }
  } satisfies StreamEnvelope,
  "StreamEnvelope.observation_phone": {
    "contract": "qorgau.v1",
    "seq": 41,
    "sent_at": "2026-10-09T09:00:04.005000Z",
    "session_id": "fx-session-0001",
    "message": {
      "type": "observation",
      "observation": {
        "observation_id": "fx-phone-120",
        "session_id": "fx-session-0001",
        "frame_id": 120,
        "t_session_ms": 4000.0,
        "wall_time": "2026-10-09T09:00:04Z",
        "source_mode": "synthetic",
        "producer": {
          "module": "phone",
          "version": "fixture-1",
          "model_id": "fixture-detector",
          "model_sha256": null,
          "config_version": null
        },
        "status": "ok",
        "quality": 0.8,
        "quality_flags": [],
        "latency_ms": 85.0,
        "kind": "phone",
        "detections": [
          {
            "bbox": {
              "x_min": 0.42,
              "y_min": 0.55,
              "x_max": 0.52,
              "y_max": 0.78
            },
            "confidence": 0.71,
            "class_name": "cell phone",
            "class_index": 67,
            "track_id": "trk-1",
            "track_quality": 0.9,
            "track_age_ms": 1600.0
          }
        ],
        "signals": [
          {
            "name": "phone_visible",
            "state": "present",
            "confidence": 0.71,
            "track_id": "trk-1",
            "reason": "detected_in_frame",
            "facts": {
              "visible_ms": 1600.0
            }
          },
          {
            "name": "phone_raised",
            "state": "absent",
            "confidence": null,
            "track_id": "trk-1",
            "reason": "track_below_raise_zone",
            "facts": {
              "rise_ratio": 0.03
            }
          },
          {
            "name": "possible_screen_capture",
            "state": "insufficient_evidence",
            "confidence": null,
            "track_id": null,
            "reason": "camera_side_not_observable",
            "facts": {}
          }
        ]
      }
    }
  } satisfies StreamEnvelope,
} as const;

export type FixtureKey = keyof typeof fixtures;
