// GENERATED by proctoring/contracts/tools/generate.py from proctor_contracts/v1.py.
// DO NOT EDIT. Owner: A01. Change requests: proctoring/handoffs/Axx/DEPENDENCIES.txt
export const CONTRACT_ID = "qorgau.v1" as const;
export const CONTRACT_VERSION = "1.1.0" as const;

export interface AbortRequest {
  reason: string;
}

export interface AnswerRecord {
  session_id: string;
  question_id: string;
  value: string | Array<string>;
  client_seq: number;
  saved_at: string;
}

export interface AnswerUpsert {
  value: string | Array<string>;
  client_seq: number;
}

/**
 * Body of every non-2xx response.
 */
export interface ApiError {
  error: ApiErrorBody;
}

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  details: Record<string, boolean | number | string>;
}

export interface AttentionObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "attention";
  face_count: number | null;
  faces: Array<FaceBox>;
  primary_face_present: boolean | null;
  head_pose: HeadPose | null;
  head_direction: Direction;
  gaze: GazeEstimate | null;
  calibration_id: string | null;
  reasons: Array<string>;
}

/**
 * 1.1. Microphone features only; audio is never recorded or transmitted. frame_id is None.
 */
export interface AudioObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "audio";
  voice_like: SignalState;
  voice_probability: number | null;
  rms_dbfs: number | null;
  noise_floor_dbfs: number | null;
  reasons: Array<string>;
}

/**
 * Normalized box in the UNMIRRORED frame: x right, y down, origin top-left.
 */
export interface BBox {
  x_min: number;
  y_min: number;
  x_max: number;
  y_max: number;
}

export interface CalibrationMsg {
  type: "calibration";
  session_id: string;
  calibration: CalibrationState;
}

export type CalibrationPhase = "not_started" | "collecting" | "completed" | "failed" | "skipped" | "cancelled";
export const CalibrationPhaseValues = ["not_started", "collecting", "completed", "failed", "skipped", "cancelled"] as const;

export interface CalibrationSkipRequest {
  reason: string;
}

export interface CalibrationState {
  calibration_id: string | null;
  phase: CalibrationPhase;
  targets: Array<CalibrationTargetStatus>;
  current_target: CalibrationTarget | null;
  message_code: string | null;
  updated_at: string;
}

export type CalibrationTarget = "center" | "left" | "right" | "up" | "down";
export const CalibrationTargetValues = ["center", "left", "right", "up", "down"] as const;

export interface CalibrationTargetRequest {
  target: CalibrationTarget;
}

export type CalibrationTargetState = "pending" | "collecting" | "ok" | "failed";
export const CalibrationTargetStateValues = ["pending", "collecting", "ok", "failed"] as const;

export interface CalibrationTargetStatus {
  target: CalibrationTarget;
  state: CalibrationTargetState;
  samples: number;
  required_samples: number;
  quality: number | null;
  message_code: string | null;
}

export type CapabilityStatus = "blocked" | "detected_only" | "unsupported" | "unverified";
export const CapabilityStatusValues = ["blocked", "detected_only", "unsupported", "unverified"] as const;

export type CheckStatus = "pass" | "warn" | "fail" | "not_run";
export const CheckStatusValues = ["pass", "warn", "fail", "not_run"] as const;

export type Component = "backend" | "capture" | "phone" | "attention" | "fusion" | "evidence" | "environment" | "audio" | "identity";
export const ComponentValues = ["backend", "capture", "phone", "attention", "fusion", "evidence", "environment", "audio", "identity"] as const;

export interface ConsentRecord {
  accepted: boolean;
  text_version: string;
  accepted_at: string;
}

export interface ConsumerMetrics {
  name: string;
  processed_fps: number;
  frames_processed: number;
  frames_skipped: number;
  errors: number;
  frame_age_ms_p50: number | null;
  frame_age_ms_p95: number | null;
  process_ms_p50: number | null;
  process_ms_p95: number | null;
}

export interface CoverageGap {
  t_start_ms: number;
  t_end_ms: number | null;
  component: Component;
  reason: string;
}

/**
 * Subject-centric direction (the student's own left/right).
 */
export type Direction = "center" | "left" | "right" | "up" | "down" | "unknown";
export const DirectionValues = ["center", "left", "right", "up", "down", "unknown"] as const;

export type EnforcementResult = "blocked" | "detected_only" | "allowed" | "failed" | "unsupported";
export const EnforcementResultValues = ["blocked", "detected_only", "allowed", "failed", "unsupported"] as const;

export type EnforcementScope = "renderer" | "window" | "app" | "os_session";
export const EnforcementScopeValues = ["renderer", "window", "app", "os_session"] as const;

export type EnvironmentAction = "shortcut_alt_tab" | "shortcut_ctrl_c" | "shortcut_ctrl_v" | "shortcut_ctrl_x" | "shortcut_ctrl_tab" | "shortcut_win" | "shortcut_print_screen" | "shortcut_alt_f4" | "focus_lost" | "focus_regained" | "foreign_window_foreground" | "new_window_blocked" | "navigation_blocked" | "devtools_blocked" | "clipboard_blocked" | "display_changed" | "exam_mode_engaged" | "exam_mode_released" | "enforcement_error";
export const EnvironmentActionValues = ["shortcut_alt_tab", "shortcut_ctrl_c", "shortcut_ctrl_v", "shortcut_ctrl_x", "shortcut_ctrl_tab", "shortcut_win", "shortcut_print_screen", "shortcut_alt_f4", "focus_lost", "focus_regained", "foreign_window_foreground", "new_window_blocked", "navigation_blocked", "devtools_blocked", "clipboard_blocked", "display_changed", "exam_mode_engaged", "exam_mode_released", "enforcement_error"] as const;

export interface EnvironmentCapabilities {
  reported_at: string;
  platform: string;
  shell_version: string;
  exam_mode_supported: boolean;
  items: Array<EnvironmentCapability>;
}

export interface EnvironmentCapability {
  action: EnvironmentAction;
  status: CapabilityStatus;
  mechanism: string;
  verified_on: string | null;
  note_ru: string | null;
}

/**
 * Allow-listed, non-sensitive details only. No window titles, no typed text, no clipboard content.
 */
export interface EnvironmentDetail {
  process_name: string | null;
  shortcut: string | null;
  duration_ms: number | null;
}

export interface EnvironmentEventAck {
  accepted: number;
  duplicates: number;
  observation_ids: Array<string>;
}

export interface EnvironmentEventBatch {
  session_id: string;
  events: Array<EnvironmentEventIn>;
}

/**
 * Sent by Electron main (A06). Backend assigns observation_id/t_session_ms on receipt.
 */
export interface EnvironmentEventIn {
  action: EnvironmentAction;
  enforcement: EnforcementResult;
  mechanism: string;
  scope: EnforcementScope;
  client_seq: number;
  client_wall_time: string;
  detail: EnvironmentDetail;
}

/**
 * Created by the backend from EnvironmentEventIn (A06). frame_id is always None.
 */
export interface EnvironmentObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "environment";
  action: EnvironmentAction;
  enforcement: EnforcementResult;
  mechanism: string;
  scope: EnforcementScope;
  client_seq: number;
  client_wall_time: string;
  detail: EnvironmentDetail;
}

export type ErrorCode = "UNAUTHORIZED" | "FORBIDDEN_ORIGIN" | "INVALID_ARGUMENT" | "PAYLOAD_TOO_LARGE" | "NOT_FOUND" | "SESSION_NOT_FOUND" | "SESSION_ACTIVE" | "SESSION_MISMATCH" | "INVALID_STATE" | "PREFLIGHT_FAILED" | "CAMERA_UNAVAILABLE" | "CAMERA_BUSY" | "CAMERA_DENIED" | "REPLAY_INVALID" | "MODEL_MISSING" | "MODEL_INVALID" | "MODULE_NOT_INTEGRATED" | "CALIBRATION_FAILED" | "STORAGE_ERROR" | "NOT_IMPLEMENTED" | "INTERNAL";
export const ErrorCodeValues = ["UNAUTHORIZED", "FORBIDDEN_ORIGIN", "INVALID_ARGUMENT", "PAYLOAD_TOO_LARGE", "NOT_FOUND", "SESSION_NOT_FOUND", "SESSION_ACTIVE", "SESSION_MISMATCH", "INVALID_STATE", "PREFLIGHT_FAILED", "CAMERA_UNAVAILABLE", "CAMERA_BUSY", "CAMERA_DENIED", "REPLAY_INVALID", "MODEL_MISSING", "MODEL_INVALID", "MODULE_NOT_INTEGRATED", "CALIBRATION_FAILED", "STORAGE_ERROR", "NOT_IMPLEMENTED", "INTERNAL"] as const;

export interface EvidenceItem {
  evidence_id: string;
  session_id: string;
  incident_id: string | null;
  kind: EvidenceKind;
  frame_id: number | null;
  t_session_ms: number;
  media_type: "image/jpeg" | "video/mp4" | "video/webm";
  sha256: string;
  size_bytes: number;
  created_at: string;
}

export type EvidenceKind = "snapshot" | "clip";
export const EvidenceKindValues = ["snapshot", "clip"] as const;

export interface ExamDefinition {
  exam_id: string;
  title: string;
  locale: "ru" | "kk";
  duration_s: number;
  is_demo: boolean;
  questions: Array<Question>;
}

/**
 * Human text is rendered by code from facts; every number in summary_ru comes from facts.
 */
export interface Explanation {
  summary_ru: string;
  summary_kk: string | null;
  facts: Array<ExplanationFact>;
  caveats_ru: Array<string>;
}

export interface ExplanationFact {
  key: string;
  value: boolean | number | string;
  unit: "ms" | "s" | "count" | "ratio" | "deg" | "none";
  label_ru: string;
}

export interface ExportFile {
  name: string;
  media_type: string;
  sha256: string;
  size_bytes: number;
}

/**
 * Integrity manifest. A hash is NOT tamper-proofing against the machine owner.
 */
export interface ExportManifest {
  contract: "qorgau.v1";
  contract_version: string;
  exported_at: string;
  session_id: string;
  source_mode: SourceMode;
  backend_version: string;
  config_versions: Record<string, string>;
  models: Array<ModelManifest>;
  files: Array<ExportFile>;
  limitations_ru: Array<string>;
}

export interface FaceBox {
  bbox: BBox;
  confidence: number | null;
  is_primary: boolean;
}

/**
 * Metadata of a captured frame. Pixels travel in-process only (see interfaces.FramePacket).
 */
export interface FramePacketMeta {
  session_id: string;
  frame_id: number;
  t_session_ms: number;
  wall_time: string;
  t_capture_mono_ns: number;
  width: number;
  height: number;
  color_format: "BGR";
  mirrored: false;
  source_mode: SourceMode;
  source_id: string;
}

/**
 * Approximate gaze. NOT eye tracking, NOT evidence of cheating.
 */
export interface GazeEstimate {
  direction: Direction;
  yaw_deg: number | null;
  pitch_deg: number | null;
  confidence: number | null;
  method: GazeMethod;
  calibrated: boolean;
}

export type GazeMethod = "head_pose_only" | "landmark_iris" | "fused";
export const GazeMethodValues = ["head_pose_only", "landmark_iris", "fused"] as const;

/**
 * Degrees, subject-centric: +yaw = student turns to THEIR right, +pitch = up, +roll = tilt to their right.
 */
export interface HeadPose {
  yaw_deg: number;
  pitch_deg: number;
  roll_deg: number;
}

export interface Health {
  component: Component;
  status: HealthStatus;
  code: string;
  message: string;
  since_t_session_ms: number | null;
  details: Record<string, boolean | number | string>;
}

export interface HealthMsg {
  type: "health";
  report: HealthReport;
}

/**
 * Health change as an observation so fusion can open technical incidents / coverage gaps.
 */
export interface HealthObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "health";
  health: Health;
}

export interface HealthReport {
  backend_version: string;
  contract_version: string;
  overall: HealthStatus;
  components: Array<Health>;
  active_session_id: string | null;
  server_time: string;
}

export type HealthStatus = "starting" | "ok" | "degraded" | "unavailable" | "error" | "stopped";
export const HealthStatusValues = ["starting", "ok", "degraded", "unavailable", "error", "stopped"] as const;

export interface HelloMsg {
  type: "hello";
  contract: "qorgau.v1";
  contract_version: string;
  backend_version: string;
  server_time: string;
}

export interface HumanReview {
  review_id: string;
  session_id: string;
  incident_id: string;
  decision: ReviewDecision;
  comment: string;
  operator: string;
  created_at: string;
  supersedes_review_id: string | null;
}

export interface HumanReviewCreate {
  decision: ReviewDecision;
  comment: string;
  operator: string;
}

/**
 * 1.1. Is the primary face the same person as enrolled at exam start? Embeddings stay in memory.
 */
export interface IdentityObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "identity";
  same_person: SignalState;
  similarity: number | null;
  enrolled: boolean;
  reasons: Array<string>;
}

export interface Incident {
  incident_id: string;
  session_id: string;
  rule_id: IncidentRule;
  category: IncidentCategory;
  state: IncidentState;
  priority: ReviewPriority;
  t_start_ms: number;
  t_end_ms: number | null;
  wall_start: string;
  wall_end: string | null;
  duration_ms: number;
  source_mode: SourceMode;
  max_confidence: number | null;
  mean_quality: number | null;
  explanation: Explanation;
  observation_ids: Array<string>;
  observation_count: number;
  trigger_frame_id: number | null;
  related_incident_ids: Array<string>;
  evidence_ids: Array<string>;
  rule_version: string;
  config_version: string;
  end_reason: IncidentEndReason | null;
  update_seq: number;
  review_status: ReviewStatus;
}

export type IncidentCategory = "phone" | "attention" | "presence" | "environment" | "technical" | "audio" | "identity" | "objects";
export const IncidentCategoryValues = ["phone", "attention", "presence", "environment", "technical", "audio", "identity", "objects"] as const;

export interface IncidentChange {
  change: IncidentChangeType;
  incident: Incident;
}

export type IncidentChangeType = "opened" | "updated" | "closed";
export const IncidentChangeTypeValues = ["opened", "updated", "closed"] as const;

export interface IncidentDetail {
  incident: Incident;
  reviews: Array<HumanReview>;
  evidence: Array<EvidenceItem>;
}

export type IncidentEndReason = "condition_cleared" | "session_finished" | "session_paused" | "session_aborted" | "source_lost" | "merged";
export const IncidentEndReasonValues = ["condition_cleared", "session_finished", "session_paused", "session_aborted", "source_lost", "merged"] as const;

export interface IncidentMsg {
  type: "incident";
  change: IncidentChange;
}

export type IncidentRule = "phone_visible" | "phone_raised" | "possible_screen_capture" | "gaze_prolonged_down" | "gaze_prolonged_side" | "face_missing" | "multiple_faces" | "environment_blocked_action" | "environment_escape" | "monitoring_degraded" | "background_speech" | "headphones_visible" | "identity_mismatch" | "foreign_object_visible" | "second_screen_visible";
export const IncidentRuleValues = ["phone_visible", "phone_raised", "possible_screen_capture", "gaze_prolonged_down", "gaze_prolonged_side", "face_missing", "multiple_faces", "environment_blocked_action", "environment_escape", "monitoring_degraded", "background_speech", "headphones_visible", "identity_mismatch", "foreign_object_visible", "second_screen_visible"] as const;

export type IncidentState = "open" | "closed";
export const IncidentStateValues = ["open", "closed"] as const;

export interface MetricsMsg {
  type: "metrics";
  metrics: RuntimeMetrics;
}

/**
 * Committed next to the module code; weights live outside Git under settings.models_dir.
 */
export interface ModelManifest {
  model_id: string;
  module: "phone" | "attention";
  task: string;
  file: string;
  format: "onnx" | "task" | "tflite" | "pt";
  version: string;
  source_url: string;
  license: string;
  sha256: string;
  size_bytes: number;
  input_size: Array<number> | null;
  class_names: Record<string, string> | null;
  prepared_at: string;
  notes: string;
}

/**
 * Discriminated union `Observation`.
 */
export type Observation = PhoneObservation | AttentionObservation | EnvironmentObservation | HealthObservation | AudioObservation | IdentityObservation;

export interface ObservationMsg {
  type: "observation";
  observation: Observation;
}

export type ObservationStatus = "ok" | "unknown" | "degraded" | "error";
export const ObservationStatusValues = ["ok", "unknown", "degraded", "error"] as const;

export interface PauseRequest {
  reason: string;
}

export interface PhoneDetection {
  bbox: BBox;
  confidence: number;
  class_name: string;
  class_index: number;
  track_id: string | null;
  track_quality: number | null;
  track_age_ms: number | null;
}

export interface PhoneObservation {
  observation_id: string;
  session_id: string;
  frame_id: number | null;
  t_session_ms: number;
  wall_time: string;
  source_mode: SourceMode;
  producer: Producer;
  status: ObservationStatus;
  quality: number | null;
  quality_flags: Array<string>;
  latency_ms: number | null;
  kind: "phone";
  detections: Array<PhoneDetection>;
  signals: Array<PhoneSignal>;
}

export interface PhoneSignal {
  name: PhoneSignalName;
  state: SignalState;
  confidence: number | null;
  track_id: string | null;
  reason: string;
  facts: Record<string, boolean | number | string>;
}

export type PhoneSignalName = "phone_visible" | "phone_raised" | "possible_screen_capture";
export const PhoneSignalNameValues = ["phone_visible", "phone_raised", "possible_screen_capture"] as const;

export interface PreflightCheck {
  check_id: PreflightCheckId;
  status: CheckStatus;
  required: boolean;
  message_code: string;
  message_ru: string;
  details: Record<string, boolean | number | string>;
}

export type PreflightCheckId = "backend" | "camera" | "lighting" | "phone_model" | "face_model" | "fusion" | "storage" | "environment_protection" | "offline_assets";
export const PreflightCheckIdValues = ["backend", "camera", "lighting", "phone_model", "face_model", "fusion", "storage", "environment_protection", "offline_assets"] as const;

export interface PreflightReport {
  session_id: string;
  source_mode: SourceMode;
  checks: Array<PreflightCheck>;
  ready: boolean;
  created_at: string;
}

/**
 * Header of a binary preview message (see CONTRACTS.md §Preview transport).
 */
export interface PreviewFrameMeta {
  session_id: string;
  frame_id: number;
  t_session_ms: number;
  wall_time: string;
  width: number;
  height: number;
  mirrored: false;
  source_mode: SourceMode;
  media_type: "image/jpeg";
  byte_length: number;
}

/**
 * Who produced a record. model_* is set when an ML model was involved.
 */
export interface Producer {
  module: string;
  version: string;
  model_id: string | null;
  model_sha256: string | null;
  config_version: string | null;
}

export interface Question {
  question_id: string;
  kind: QuestionKind;
  prompt: string;
  options: Array<QuestionOption>;
  max_length: number | null;
}

export type QuestionKind = "single_choice" | "multi_choice" | "short_text";
export const QuestionKindValues = ["single_choice", "multi_choice", "short_text"] as const;

export interface QuestionOption {
  option_id: string;
  text: string;
}

export type ReviewDecision = "confirmed" | "dismissed" | "inconclusive";
export const ReviewDecisionValues = ["confirmed", "dismissed", "inconclusive"] as const;

/**
 * Priority of HUMAN REVIEW, from transparent rules. Not a probability of guilt.
 */
export type ReviewPriority = "low" | "medium" | "high";
export const ReviewPriorityValues = ["low", "medium", "high"] as const;

export type ReviewStatus = "pending" | "confirmed" | "dismissed" | "inconclusive";
export const ReviewStatusValues = ["pending", "confirmed", "dismissed", "inconclusive"] as const;

/**
 * Review queue priority; grey is insufficient coverage, never clearance or guilt.
 */
export type ReviewZone = "green" | "yellow" | "red" | "grey";
export const ReviewZoneValues = ["green", "yellow", "red", "grey"] as const;

export interface RuntimeMetrics {
  session_id: string | null;
  t_session_ms: number | null;
  window_s: number;
  capture_fps: number;
  frames_captured: number;
  frames_dropped: number;
  consumers: Array<ConsumerMetrics>;
  e2e_latency_ms_p50: number | null;
  e2e_latency_ms_p95: number | null;
}

export interface SessionCreate {
  source: SourceConfig;
  exam_id: string;
  student_label: string | null;
  consent: ConsentRecord;
  retain_media: boolean;
}

export interface SessionInfo {
  session_id: string;
  state: SessionState;
  source: SourceConfig;
  source_mode: SourceMode;
  exam_id: string;
  student_label: string | null;
  retain_media: boolean;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
  exam_started_t_ms: number | null;
  paused_total_ms: number;
  calibration: CalibrationState;
  contract_version: string;
  backend_version: string;
  last_error: ApiErrorBody | null;
}

export type SessionState = "created" | "preflight" | "calibrating" | "ready" | "running" | "paused" | "finished" | "aborted" | "failed";
export const SessionStateValues = ["created", "preflight", "calibrating", "ready", "running", "paused", "finished", "aborted", "failed"] as const;

export interface SessionStateMsg {
  type: "session_state";
  session: SessionInfo;
}

export interface SessionSummary {
  session: SessionInfo;
  observed_ms: number;
  paused_ms: number;
  gaps: Array<CoverageGap>;
  incidents_total: number;
  incidents_by_rule: Record<string, number>;
  reviews_by_decision: Record<string, number>;
  limitations_ru: Array<string>;
  review_zone: ReviewZone | null;
  review_zone_reasons_ru: Array<string>;
  review_zone_rule_version: string | null;
}

export type SignalState = "present" | "absent" | "unknown" | "insufficient_evidence";
export const SignalStateValues = ["present", "absent", "unknown", "insufficient_evidence"] as const;

export interface SourceConfig {
  mode: SourceMode;
  camera_index: number;
  replay_id: string | null;
  width: number;
  height: number;
  fps: number;
}

/**
 * Where frames/observations come from. Always visible in UI and reports.
 */
export type SourceMode = "live" | "replay" | "synthetic";
export const SourceModeValues = ["live", "replay", "synthetic"] as const;

export interface StreamEnvelope {
  contract: "qorgau.v1";
  seq: number;
  sent_at: string;
  session_id: string | null;
  message: StreamPayload;
}

export interface StreamErrorMsg {
  type: "error";
  error: ApiErrorBody;
}

/**
 * Discriminated union `StreamPayload`.
 */
export type StreamPayload = HelloMsg | SessionStateMsg | ObservationMsg | IncidentMsg | HealthMsg | MetricsMsg | CalibrationMsg | StreamErrorMsg;
