"""Generate JSON Schema + TypeScript types from classroom.contracts.models (owner: T01).

    python -m classroom.contracts.generate           # write schema/classroom.v1.schema.json, ts/classroom-v1.generated.ts
    python -m classroom.contracts.generate --check   # exit 1 when the committed files are out of date

TypeScript describes fully serialized JSON: optional Python fields with a default are optional-or-null in TS.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter
from pydantic.json_schema import models_json_schema

from . import models as m

HERE = Path(__file__).resolve().parent
SCHEMA_PATH = HERE / "schema" / "classroom.v1.schema.json"
TS_PATH = HERE / "ts" / "classroom-v1.generated.ts"
FIXTURES_DIR = HERE / "fixtures" / "v1"
REF = "#/$defs/{model}"


def build_schema() -> dict[str, Any]:
    _, top = models_json_schema([(model, "validation") for model in m.SCHEMA_MODELS], ref_template=REF)
    defs: dict[str, Any] = dict(top.get("$defs", {}))
    for name, union in m.UNIONS.items():
        schema = TypeAdapter(union).json_schema(ref_template=REF)
        defs.update(schema.pop("$defs", {}))
        defs[name] = schema
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://qorgau.local/classroom/classroom.v1.schema.json",
        "title": "Qorgau Classroom contracts",
        "x-contract-id": m.CONTRACT_ID,
        "x-contract-version": m.CONTRACT_VERSION,
        "x-wire-protocol": m.WIRE_PROTOCOL,
        "x-wire-extension": m.WIRE_EXTENSION,
        "$defs": {k: defs[k] for k in sorted(defs)},
    }


# ------------------------------------------------------------------------------------------- TypeScript
def _ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts = []
            for sub in schema[key]:
                t = _ts(sub)
                if t not in parts:
                    parts.append(t)
            return " | ".join(parts)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        inner = _ts(schema.get("items", {}))
        return f"Array<{inner}>"
    if kind == "object":
        if "properties" in schema:
            return _object(schema, inline=True)
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict) and extra:
            return f"Record<string, {_ts(extra)}>"
        return "Record<string, unknown>"
    return "unknown"


def _object(schema: dict[str, Any], inline: bool = False) -> str:
    required = set(schema.get("required", []))
    lines = []
    for name, prop in schema.get("properties", {}).items():
        opt = "" if name in required else "?"
        desc = prop.get("description")
        doc = f"  /** {desc} */\n" if desc and not inline else ""
        lines.append(f"{doc}  {name}{opt}: {_ts(prop)};")
    body = "\n".join(lines)
    return "{\n" + body + "\n}" if not inline else "{ " + " ".join(l.strip() for l in lines) + " }"


def build_ts(schema: dict[str, Any]) -> str:
    out = [
        "// GENERATED by `python -m classroom.contracts.generate` from classroom/contracts/models.py — do not edit.",
        f"// Contract {m.CONTRACT_ID} {m.CONTRACT_VERSION}; student wire {m.WIRE_PROTOCOL} (+ additive {m.WIRE_EXTENSION}).",
        "",
        f'export const CONTRACT_ID = "{m.CONTRACT_ID}";',
        f'export const CONTRACT_VERSION = "{m.CONTRACT_VERSION}";',
        f'export const WIRE_PROTOCOL = "{m.WIRE_PROTOCOL}";',
        "",
    ]
    for name, sub in schema["$defs"].items():
        doc = sub.get("description")
        if doc:
            out.append("/** " + " ".join(doc.split()) + " */")
        if sub.get("type") == "object" and "properties" in sub:
            out.append(f"export interface {name} {_object(sub)}")
        else:
            out.append(f"export type {name} = {_ts(sub)};")
        out.append("")
    return "\n".join(out)


def render() -> tuple[str, str]:
    schema = build_schema()
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n", build_ts(schema)


def render_fixtures() -> dict[Path, str]:
    from .fixtures_src import build

    return {FIXTURES_DIR / f"{name}.json": json.dumps(data, indent=2, ensure_ascii=False) + "\n" for name, data in sorted(build().items())}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m classroom.contracts.generate")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    schema_text, ts_text = render()
    fixtures = render_fixtures()
    outputs = {SCHEMA_PATH: schema_text, TS_PATH: ts_text, **fixtures}
    if args.check:
        stale = [p for p, text in outputs.items() if not p.is_file() or p.read_text(encoding="utf-8") != text]
        stale += [p for p in FIXTURES_DIR.glob("*.json") if p not in fixtures]  # orphaned fixture files
        for p in stale:
            print(f"OUT OF DATE: {p.relative_to(HERE.parent.parent)}")
        print(f"classroom contracts {m.CONTRACT_VERSION}: {'generated files up to date' if not stale else 'regenerate with python -m classroom.contracts.generate'}")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    for orphan in [p for p in FIXTURES_DIR.glob("*.json") if p not in fixtures]:
        orphan.unlink()
    print(f"wrote {SCHEMA_PATH.name} ({len(schema_text)} B), {TS_PATH.name} ({len(ts_text)} B), {len(fixtures)} fixtures")
    return 0


if __name__ == "__main__":
    sys.exit(main())
