#!/usr/bin/env python3
"""Generate JSON Schema + TypeScript wire types + typed TS fixtures from proctor_contracts.v1.

Single source of truth: proctoring/contracts/python/proctor_contracts/v1.py (owner A01).

    python contracts/tools/generate.py          # write generated files
    python contracts/tools/generate.py --check  # exit 1 if generated files are stale

Outputs (do not edit by hand):
    contracts/schema/v1/qorgau.v1.schema.json
    contracts/ts/qorgau-v1.generated.ts
    contracts/ts/fixtures.generated.ts

TypeScript types describe FULLY SERIALIZED messages: every key is present (null when empty).
Requests built in TypeScript therefore also send every key explicitly.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]  # proctoring/contracts
sys.path.insert(0, str(ROOT / "python"))

from pydantic import TypeAdapter  # noqa: E402
from pydantic.json_schema import models_json_schema  # noqa: E402

from proctor_contracts import v1  # noqa: E402

SCHEMA_OUT = ROOT / "schema" / "v1" / "qorgau.v1.schema.json"
TS_OUT = ROOT / "ts" / "qorgau-v1.generated.ts"
TS_FIXTURES_OUT = ROOT / "ts" / "fixtures.generated.ts"
FIXTURES_DIR = ROOT / "fixtures" / "v1"

HEADER = (
    "// GENERATED by proctoring/contracts/tools/generate.py from proctor_contracts/v1.py.\n"
    "// DO NOT EDIT. Owner: A01. Change requests: proctoring/handoffs/Axx/DEPENDENCIES.txt\n"
)

# Named unions (Python Annotated[Union[...]] aliases) -> TS alias names
NAMED_UNIONS = {"Observation": v1.Observation, "StreamPayload": v1.StreamPayload}


def build_schema() -> dict:
    _, schema = models_json_schema(
        [(m, "validation") for m in v1.WIRE_MODELS],
        ref_template="#/$defs/{model}",
        title="Qorgau Exam contracts v1",
    )
    defs = schema.setdefault("$defs", {})
    for alias, tp in NAMED_UNIONS.items():
        sub = TypeAdapter(tp).json_schema(ref_template="#/$defs/{model}", mode="validation")
        defs.update(sub.pop("$defs", {}))
        defs[alias] = sub
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://qorgau.local/contracts/qorgau.v1.schema.json",
        "title": "Qorgau Exam contracts v1",
        "x-contract-id": v1.CONTRACT_ID,
        "x-contract-version": v1.CONTRACT_VERSION,
        "$defs": dict(sorted(defs.items())),
    }


class TsGen:
    def __init__(self, defs: dict):
        self.defs = defs
        self.union_alias = {}
        for alias in NAMED_UNIONS:
            refs = self._union_refs(defs[alias])
            if refs:
                self.union_alias[refs] = alias

    @staticmethod
    def _union_refs(node: dict) -> frozenset[str] | None:
        options = node.get("oneOf") or node.get("anyOf")
        if not options or not all("$ref" in o for o in options):
            return None
        return frozenset(o["$ref"].rsplit("/", 1)[-1] for o in options)

    def expr(self, node: dict, *, use_alias: bool = True) -> str:
        if "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        if "const" in node:
            return json.dumps(node["const"], ensure_ascii=False)
        if "enum" in node:
            return " | ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
        for key in ("oneOf", "anyOf"):
            if key in node:
                refs = self._union_refs(node)
                if use_alias and refs and refs in self.union_alias:
                    return self.union_alias[refs]
                parts = []
                for option in node[key]:
                    part = self.expr(option)
                    if part not in parts:
                        parts.append(part)
                return " | ".join(f"({p})" if "|" in p and len(node[key]) > 1 and p != "null" else p for p in parts)
        t = node.get("type")
        if isinstance(t, list):
            return " | ".join(self.expr({**node, "type": x}) for x in t)
        if t == "null":
            return "null"
        if t == "string":
            return "string"
        if t in ("integer", "number"):
            return "number"
        if t == "boolean":
            return "boolean"
        if t == "array":
            inner = self.expr(node.get("items", {}))
            return f"Array<{inner}>"
        if t == "object":
            if "properties" in node:
                raise ValueError(f"inline object types are not supported: {node}")
            ap = node.get("additionalProperties", True)
            inner = "unknown" if ap is True else self.expr(ap)
            return f"Record<string, {inner}>"
        if node == {}:
            return "unknown"
        raise ValueError(f"unsupported schema node: {node}")

    @staticmethod
    def doc(text: str | None, indent: str = "") -> str:
        if not text:
            return ""
        lines = [ln.rstrip() for ln in text.strip().splitlines()]
        body = "\n".join(f"{indent} * {ln}".rstrip() for ln in lines)
        return f"{indent}/**\n{body}\n{indent} */\n"

    def render(self) -> str:
        out = [HEADER, f'export const CONTRACT_ID = "{v1.CONTRACT_ID}" as const;\n']
        out.append(f'export const CONTRACT_VERSION = "{v1.CONTRACT_VERSION}" as const;\n\n')
        for name, node in self.defs.items():
            if name in NAMED_UNIONS:
                out.append(self.doc(f"Discriminated union `{name}`.") + f"export type {name} = {self.expr(node, use_alias=False)};\n\n")
            elif "enum" in node:
                values = ", ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
                out.append(self.doc(node.get("description")))
                out.append(f"export type {name} = {self.expr(node)};\n")
                out.append(f"export const {name}Values = [{values}] as const;\n\n")
            elif node.get("type") == "object" and "properties" in node:
                out.append(self.doc(node.get("description")))
                out.append(f"export interface {name} {{\n")
                for prop, sub in node["properties"].items():
                    desc = sub.get("description")
                    if desc:
                        out.append(self.doc(desc, "  "))
                    out.append(f"  {prop}: {self.expr(sub)};\n")
                out.append("}\n\n")
            else:
                raise ValueError(f"unsupported top-level def {name}: {node}")
        return "".join(out).rstrip() + "\n"


def load_fixtures() -> list[tuple[str, str, dict]]:
    """Fixtures are named <ModelName>.<case>.json; returns (key, model, normalized json)."""
    models = {m.__name__: m for m in v1.WIRE_MODELS}
    result = []
    for path in sorted(FIXTURES_DIR.glob("*.json")):
        model_name, _, case = path.stem.partition(".")
        if model_name not in models or not case:
            raise SystemExit(f"fixture {path.name}: expected <WireModel>.<case>.json")
        raw = json.loads(path.read_text(encoding="utf-8"))
        normalized = models[model_name].model_validate(raw).model_dump(mode="json")
        result.append((path.stem, model_name, normalized))
    return result


def render_ts_fixtures(fixtures: list[tuple[str, str, dict]]) -> str:
    names = sorted({m for _, m, _ in fixtures})
    out = [HEADER, "// Contract fixtures (marked synthetic data), typed with `satisfies` so tsc checks them.\n"]
    out.append(f"import type {{ {', '.join(names)} }} from \"./qorgau-v1.generated\";\n\n")
    out.append("export const fixtures = {\n")
    for key, model, data in fixtures:
        body = json.dumps(data, ensure_ascii=False, indent=2).replace("\n", "\n  ")
        out.append(f"  {json.dumps(key)}: {body} satisfies {model},\n")
    out.append("} as const;\n\nexport type FixtureKey = keyof typeof fixtures;\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    schema = build_schema()
    outputs = {
        SCHEMA_OUT: json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        TS_OUT: TsGen(schema["$defs"]).render(),
        TS_FIXTURES_OUT: render_ts_fixtures(load_fixtures()),
    }
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    rel = [str(p.relative_to(ROOT.parent)) for p in stale]
    if args.check:
        if stale:
            print("STALE generated contract files (run contracts/tools/generate.py):", *rel, sep="\n  ")
            return 1
        print(f"contracts {v1.CONTRACT_ID} {v1.CONTRACT_VERSION}: generated files up to date")
        return 0
    print("written:" if rel else "nothing to write", *rel, sep="\n  ")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
